### ISSUE TITLE
Match shopping cart to historical customer

### ISSUE THREAD

**Issue by cjswedes** [cjswedes/real-wear#7]
What will the user see/do?
User clicks ”Match to Customer” button on shopping cart page
User is then shown a historical customer profile if one exists

What action will our system perform?
Perform some sort of similarity measure between their cart, and the receipts in the historical data to find a similar item.

We could possible expand this to include some sort of association rule mining functionality. I think that could be useful to a user.

What tasks should be done to accomplish that?
- [] Backend: create endpoint that performs the cart analysis and returns the proper response.  Is given a list of item ids, and must return customer data if one exists
- [ ] Frontend: Add the button to initiate the action, and then add the view that will be displayed when the user receives the customer profile.

**Comment by xunzhou** [comment]
not in implementation plan.
